# Generated by Django 4.2.7 on 2024-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contact_us_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
